[package]
name = "prompts"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
utils = { path = "../utils" }
colored = "3.0.0"
comfy-table = "7.1.4"
inquire = "0.7.5"
ctrlc = "3.4.5"
