[package]
name = "pwiz"
version = "1.0.0"
edition = "2021"

[dependencies]
model = { path = "./model" }
prompts = { path = "./prompts" }

colored = "3.0.0"
dotenvy = "0.15.7"
inquire = "0.7.5"
polodb_core = "5.1.3"
serde = "1.0.217"
comfy-table = "7.1.3"
